### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

### ISSUE THREAD

**Issue by Smoodie7** [odwyersoftware/mega.py#101]
Python 3.11
Issue:
`Traceback (most recent call last):
  File "/Users/Rayane/Documents/Projects/PyCharm/pythonProject/startupExplorer.py", line 5, in <module>
    from mega import Mega
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mega/__init__.py", line 1, in <module>
    from .mega import Mega  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mega/mega.py", line 18, in <module>
    from tenacity import retry, wait_exponential, retry_if_exception_type
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 33, in <module>
    class AsyncRetrying(BaseRetrying):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 41, in AsyncRetrying
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

Process finished with exit code 1`

I think mega.py may need an general support update

**Comment by Lednik7** [comment]
run with python 3.10 for fix

**Comment by Beefybananas** [comment]
> run with python 3.10 for fix

If the package is not compatible with Python3.11, there should be an entry in the setup.cfg file setting the _python_requires_ option specifying the supported version(s).

**Comment by nemesis668** [comment]
Any fix for this yet? Instead of using older versions of python?

**Comment by rasenganai** [comment]
!pip install tenacity --upgrade
