### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by wxrayut** [odwyersoftware/mega.py#107]
(env) PS C:\Users\sh1n\Desktop\s-v1.4> python testfunc.py
Traceback (most recent call last):
  File "C:\Users\sh1n\Desktop\s-v1.4\testfunc.py", line 4, in <module>
    from mega import Mega
  File "C:\Users\sh1n\Desktop\s-v1.4\env\Lib\site-packages\mega\__init__.py", line 1, in <module>
    from .mega import Mega  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sh1n\Desktop\s-v1.4\env\Lib\site-packages\mega\mega.py", line 18, in <module>
    from tenacity import retry, wait_exponential, retry_if_exception_type
  File "C:\Users\sh1n\Desktop\s-v1.4\env\Lib\site-packages\tenacity\__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
  File "C:\Users\sh1n\Desktop\s-v1.4\env\Lib\site-packages\tenacity\_asyncio.py", line 33, in <module>
    class AsyncRetrying(BaseRetrying):
  File "C:\Users\sh1n\Desktop\s-v1.4\env\Lib\site-packages\tenacity\_asyncio.py", line 41, in AsyncRetrying
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

**Comment by Renaissoft** [comment]
The problem is that the mega.py module relies on an old version of the tenacity module which does not work properly with recent versions of Python.  You can downgrade to an earlier version of Python, or, if you want to get your hands dirty you can make a few edits to the tenacity _asyncio.py file to make it work with modern Python versions.

Basically, where you see:

```
@asyncio.coroutine
def call(self, fn, *args, **kwargs):
```

replace that with:

`async def call(self, fn, *args, **kwargs):`
 
and wherever you see:

`yield from`

replace that with:

`await`

**Comment by wxrayut** [comment]
thx u so much. but I've just added the comment `# @asyncio.coroutine`, and now it seems to be working normally.
