### ISSUE TITLE
Python 3.11+ Version

### ISSUE THREAD

**Issue by nemesis668** [odwyersoftware/mega.py#110]
Is there a working version for Python 3.11 and above yet?

TIA

**Comment by nnilayy** [comment]
@nemesis668, I dont think so, I was trying to run the code with `Python 3.11.4` but encountered the following coroutine error:

`AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?`

But after switching to `Python 3.10` version (mine was `Python 3.10.11`), the issue was resolved and the code was running just fine.

**Comment by dshaw0004** [comment]
This package is not working for python3.11+ because of one of the required package **TENACITY**.
If you properly read the error for the source of it, you will find that the error is occuring at the line number 42 of **_asyncio.py** file in the **Tenacity** package.

## Explanation of the error

As much I know Python3.11 have remove the decorator **`@asyncio.coroutine`** and the package **tenacity** is using this decorator. But **tenacity** is not the real problem maker. The real problem is this package's `requirements.txt`. This package require **tenacity** version **5.1.5** which is compatible with **Python 3.10** but will not work with higher versions. `requirements.txt` have not been updated in past 4 years.

## Solution

As I am writing the current version of tenacity is `9.0.0`. I have manually reinstalled the latest version of **tenacity** and this package is working. And for your knowledge I am using **`Python 3.12.3`**. 

**To fix this issue manually update tenacity package**

> Finally, if you are using **python3.11** and get any other kind of error while using **tenacity==9.0.0**, try previous version of it. And let me know what happens.

**Comment by itsMGA** [comment]
Not sure what this answer is or how is this ok, while this lib is clearly broken by the update
`` pip install tenacity
Collecting tenacity
  Using cached tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Using cached tenacity-9.0.0-py3-none-any.whl (28 kB)
Installing collected packages: tenacity
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mega-py 1.0.8 requires tenacity<6.0.0,>=5.1.5, but you have tenacity 9.0.0 which is incompatible.
Successfully installed tenacity-9.0.0
```

**Comment by itsMGA** [comment]
For refferance with tenacity > 6 raises
`Traceback (most recent call last):
  File "/home/s3ll_svfiles/baks/backup_fs.py", line 200, in <module>
    selected_action()
  File "/home/s3ll_svfiles/baks/backup_fs.py", line 131, in dump
    m = init_mega()
        ^^^^^^^^^^^
  File "/home/s3ll_svfiles/baks/backup_fs.py", line 100, in init_mega
    m = mega.login(MEGA_EMAIL, MEGA_PASSWORD)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mega/mega.py", line 46, in login
    self._login_user(email, password)
  File "/usr/local/lib/python3.11/site-packages/mega/mega.py", line 73, in _login_user
    resp = self._api_request({'a': 'us', 'user': email, 'uh': user_hash})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 367, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mega/mega.py", line 188, in _api_request
    raise RequestError(int_resp)
mega.errors.RequestError: ENOENT, Object (typically, node or user) not found
`

What version exactly works for you?

**Comment by dshaw0004** [comment]
I am using tenacity verison 9.0.0 while python version is 3.12.3 and my os
is ubuntu 24.04.
[image: Screenshot from 2024-09-09 20-35-03.png]
In a fresh new virtual environment I have install the package using pip so
I am getting the error about coroutines. And I know code is wrong I did not
notice that i copied the code wrongly from docs.
[image: Screenshot from 2024-09-09 20-35-36.png]
then I update tenacity using `pip3 install tenacity -U`. Ignoring the error
I fixes the code then run it.
[image: Screenshot from 2024-09-09 21-08-20.png]
here is the result.

**Comment by dshaw0004** [comment]
While testing I got this error too. After debugging it turns out that my
password was not right. Since I am getting the password from another file,
it contains a newline character ('\n') at the end which was causing the
error.
