### ISSUE TITLE
Download File Error

### ISSUE THREAD

**Issue by Xieyt** [odwyersoftware/mega.py#25]
When Downloading File state-home-water-alok-projects-enclol-work-dir_to_back.info having this issue 

```
('mbpS0SjS', {'h': 'mbpS0SjS', 'p': 'fKwVUDgB', 'u': 'KqPVDPk5RlM', 't': 0, 'a': {'n': 'state-home-water-alok-projects-enclol-work-dir_to_back.info'}, 'k': (3008924797, 1032499355, 1615942575, 308268957), 's': 0, 'ts': 1599594789, 'iv': (1504284862, 1817208414, 0, 0), 'meta_mac': (0, 0), 'key': (3941670083, 1373296325, 1615942575, 308268957, 1504284862, 1817208414, 0, 0)})


Traceback (most recent call last):
  File "enc_beta1.py", line 135, in <module>
    uploadlogic("./dir_to_back")
  File "enc_beta1.py", line 132, in uploadlogic
    update_logic(dic_files, cloud_state_dirname, mega_object)
  File "enc_beta1.py", line 63, in update_logic
    mega_object.download(file_to_get)
  File "/home/water/alok/projects/enclol/lib/python3.8/site-packages/mega/mega.py", line 564, in download
    return self._download_file(file_handle=None,
  File "/home/water/alok/projects/enclol/lib/python3.8/site-packages/mega/mega.py", line 741, in _download_file
    if (file_mac[0] ^ file_mac[1],
IndexError: tuple index out of range
```

**Comment by Crafto1337** [comment]
I am having the same problem
