### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by lithium-umbreon** [odwyersoftware/mega.py#43]
When logging in with my email and password I get this:
```
Traceback (most recent call last):
  File "mega_test.py", line 3, in <module>
    m = Mega.login("email here", "password here")
  File "/home/lithium/.local/lib/python3.8/site-packages/mega/mega.py", line 46, in login
    self._login_user(email, password)
AttributeError: 'str' object has no attribute '_login_user'
```

**Comment by tomahocbc** [comment]
The same problem here
